baseURL = 'https://thoughts.yopa.dev/'
languageCode = 'fr-fr'
title = 'Thoughts'
theme = 'thoughts'

[params]
    dateFormat = "02/01/2006"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'dracula'
    tabWidth = 4